# Exported from Render on 2026-03-17T14:08:45Z
version: "1"
projects:
- name: Minigis
  environments:
  - name: Production
    services:
    - type: web
      name: Mini-QGIS-Online-1
      runtime: docker
      repo: https://github.com/solutionstechnologyinformation-beep/Mini-QGIS-Online
      plan: free
      envVars:
      - key: Python
        sync: false
      region: oregon
      dockerContext: pip install -r backend/requirements.txt
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
      buildFilter:
        paths:
        - Build Command
    - type: web
      name: Mini-QGIS-Online
      runtime: rust
      repo: https://github.com/solutionstechnologyinformation-beep/Mini-QGIS-Online
      plan: free
      region: oregon
      buildCommand: cargo build --release
      startCommand: https://target/release/mini-qgis-online
      domains:
      - miniqgis.com.br
      - www.miniqgis.com.br
      autoDeployTrigger: commit
